name = "rollup-a"
public_rpc = "https://rpc-a.testnet.compose.network"
explorer = "https://rollup-a.explorer.compose.network"
chain_id = 61110

[addresses]
Mailbox = "0x2498eF6bc1476652F5a47C50FAffBEa39Abbc4e5"

[genesis]
l2_time = 1760691360

[sequencer]
host = "hoodi-op-stack-a-geth"
port = 9898
auth_pubkeys = []
